### ISSUE TITLE
!addcommand feature requrest

### ISSUE THREAD

**Issue by iaxx** [MemeLabs/modbot#1]
simple quick and dirty command for random issues. 

desired input
!addcommand [command] [text] 
desired output 
![command] [text]

**Comment by xDashh** [comment]
added via https://github.com/MemeLabs/modbot/commit/585c41ebb92f0d06a9a108cc216258e565298ea5 and https://github.com/MemeLabs/modbot/commit/c315bd65950a1229e836839d15cbdc84adf88124
